#include "hal_data.h"
#include "debug_uart/uart.h"
#include "debug_gpt/gpt.h"

extern int gpt_flag;
extern int uart2_flag;
extern int uart3_flag;
extern int uart4_flag;
extern int uart5_flag;
extern uint8_t RData2[255];
extern uint8_t RData4[255];

int dataid_int = 0;
uint8_t strdataid_int[32] = {0};
float dataversion = 0 ;
uint8_t strdataversion[32] = {0};
uint8_t dataid[32] = {0};
float datavalue = 0;
uint8_t strdatavalue[32] = {0};

uint8_t TData[9] = {0};

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{

    UART2_Init();  
    UART5_Init();  
    UART3_Init(); 
    UART4_Init(); 

    gpt0_init();

    while(1)
    {
        if (uart2_flag == 1){
			if(RData2[3] == 48){
				printf_string("t1.txt","STOP");
			}else{
				switch(RData2[1]){
					case 0x00:
						printf_string("t1.txt","STOP");
						break;
					case 0x01:
						printf_string("t1.txt","AHEAD");
						break;
					case 0x02:
						printf_string("t1.txt","BEHIND");
						break;
					case 0x03:
						printf_string("t1.txt","LEFT");
						break;
					case 0x04:
						printf_string("t1.txt","RIGHT");
						break;
				}
			}
			if(RData2[1]==0x0E){
			TData[0] = RData2[2];
			TData[1] = RData2[3] + 48;
			}
			else{
			TData[0] = RData2[1] + 48;
			TData[1] = RData2[2] + 48;
			TData[2] = RData2[3] + 48;
			TData[3] = RData2[4] + 48;
			TData[4] = RData2[5] + 48;
			TData[5] = RData2[6] + 48;
			TData[6] = RData2[7] + 49;
			TData[7] = RData2[8] + 48;
			TData[8] = RData2[9] + 48;}
			printf_number("n0.val",TData[1]-48);
			printf_number("n1.val",TData[3]-48);
			printf_number("n2.val",TData[4]-48);
            R_SCI_UART_Write(&g_uart3_ctrl, &TData,9);
            /* 同步发送：等待前一次 TX 完全结束后再发新数据 */
            while (uart3_send_complete_flag == false);
            uart3_send_complete_flag = false;
            uart2_flag = 0;
        }

		if (uart4_flag == 1){
			sscanf((char *)RData4,"{\"id\":\"%d\",\"version\":\"%f\",\"params\":{\"%31[^\"]\":\"%[^\"]\"}}", &dataid_int, &dataversion, dataid, strdatavalue);
			
			if(strdatavalue[2] == ':'){
				printf_string("t3.txt",(char*)strdatavalue);
				timedata[0] = strdatavalue[0];
				timedata[1] = strdatavalue[1];
				timedata[2] = strdatavalue[2];
				timedata[3] = strdatavalue[3];
				timedata[4] = strdatavalue[4];
			}
			else{	
				sscanf((char*)strdatavalue,"%f",&datavalue);
				uint8_t buffer[20];
				sprintf((char*)buffer, "%.4f", datavalue);
				sscanf((char*)buffer, "%f", &datavalue);
			}
			
			if(dataid[0] == 'i' && dataid[1] == 'm' && dataid[2] == 'u'){
				if(dataid[4] == 'x'){
					printf_float("x0.val", datavalue);
					imu_x = datavalue;
				}
				else if(dataid[4] == 'y'){
					printf_float("x1.val", datavalue);
					imu_y = datavalue;
				}
				else if(dataid[4] == 'z'){
					printf_float("x2.val", datavalue);
					imu_z = datavalue;
				}
			}
			else if(dataid[0] == 'd' && dataid[1] == 'h' && dataid[2] == 't'){
				printf_float("x3.val", datavalue);
				dht11 = datavalue;
			}
	 		else if(dataid[0] == 'h' && dataid[1] == 'u' && dataid[2] == 'm'){
				printf_float("x4.val", datavalue);
				humi = datavalue;
			}
			else if(dataid[0] == 't' && dataid[1] == 'e' && dataid[2] == 'm'){
				printf_float("x5.val", datavalue);
				temp = datavalue;
			}
			else if(dataid[0] == 'P' && dataid[1] == 'H' ){
				printf_float("x6.val", datavalue);
				ph = datavalue;
			}
			else if(dataid[0] == 'c' && dataid[1] == 'o' && dataid[2] == 'n'){
				printf_float("x7.val", datavalue);
				cond = datavalue;
			}
			else if(dataid[0] == 't' && dataid[1] == 'u' && dataid[2] == 'r'){
				printf_float("x8.val", datavalue);
				turb = datavalue;
			}
			memset(dataid, 0, sizeof(dataid));
			memset(strdatavalue, 0, sizeof(strdatavalue));
			uart4_flag = 0;
		}

		if (uart5_flag == 1){
			 printf_string("password.txt","123456");
			 uart5_flag = 0;
		}

        if (gpt_flag == 1)
        {
			printf_string("t3.txt",(char*)timedata);
			printf_float("x0.val", imu_x);
			printf_float("x1.val", imu_y);
			printf_float("x2.val", imu_z);
			printf_float("x3.val", dht11);
			printf_float("x4.val", humi);
			printf_float("x5.val", temp);
			printf_float("x6.val", ph);
			printf_float("x7.val", cond);
			printf_float("x8.val", turb);
            gpt_flag = 0;
        }
    }

    /* TODO: add your own code here */

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
